production:
  zm_breakout_client_id: process.env.ZM_BREAKOUT_CLIENT_ID
  zm_breakout_client_secret: process.env.ZM_BREAKOUT_CLIENT_SECRET
  zm_breakout_redirect_url: process.env.ZM_BREAKOUT_REDIRECT_URL
development:
  zm_breakout_client_id: <%= ENV['ZM_BREAKOUT_CLIENT_ID'] %>
  zm_breakout_client_secret: <%= ENV['ZM_BREAKOUT_CLIENT_SECRET'] %>
  zm_breakout_redirect_url: <%= ENV['ZM_BREAKOUT_REDIRECT_URL'] %>